### ISSUE TITLE
GPU workaround troubleshooting

### ISSUE THREAD

**Issue by Echisholm21** [VIAME/VIAME#110]
Hello!

This is not an issue with the VIAME software directly but I am hoping you can help. 

I am attempting to run VIAME on a Windows Laptop, with an Intel 620 Graphics card and running into some roadblocks. From what I understand CUDA is mandatory for VIAME pipelines to execute (trying to run any pipelines currently gives me an error "Cannot find CUDA"), and CUDA is not compatible with Intel graphics cards. I have been working around this issue with other machine learning libraries (Keras, Tensorflow, Pytorch) by using Google Colab (which provides a free GPU via cloud computing). I am wondering if there is any way at all it would be possible for me to run VIAME without upgrading my laptop/ hardware. I have seen OpenCL suggested as an alternative to CUDA, will this function with VIAME?

Thanks so much for your help!

Emily

**Comment by russelldj** [comment]
If you are installing from a prebuilt binary, I believe you should be able to use a [CPU-only one](https://data.kitware.com/api/v1/item/5fb9ff7350a41e3d196659df/download) found under the [installation section](https://github.com/VIAME/VIAME#installations). This will likely give you restricted functionality. I don't believe OpenCL would help you since these deep learning libraries have a hard dependency on CUDA. 

Disclaimer: I'm a relatively new dev on this project, so take this with a grain of salt.

**Comment by russelldj** [comment]
Also you should be able to try [VIAME Web](https://viame.kitware.com/l), which allows you to run experiments in browser.

**Comment by Echisholm21** [comment]
Thank you for the suggestion! I have since upgraded my computer to a model with CUDA capabilities. I did use the CPU version for a short time though and found that it worked well on my old laptop.
